on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check README is not empty
              run: test -s README.md
        
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Install pytest
              run: pip install -U pytest
            
            - name: Install pytest-cov
              run: pip install pytest-cov --cov-fail-under=80

            - name: Run tests
              run: pytest --cov=app

