name: Deployment Lab

on:
    push:
        branches:
            - main

jobs:
    build:
        name: build            
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build artifact
              run: echo "Commit ${{ github.sha }}" > app.txt

            - uses: actions/upload-artifact@v4
              with: 
                name: deployment-artifact
                path: app.txt
    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: test

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: deployment-artifact
            
            - name: Deploy artifact
              run: cat app.txt